FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY apps/docs/ ./apps/docs/
WORKDIR /app/apps/docs
RUN npm run build

FROM node:18-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/apps/docs/package.json ./apps/docs/
COPY --from=builder /app/apps/docs/node_modules ./apps/docs/node_modules
COPY --from=builder /app/apps/docs/.next/standalone ./
COPY --from=builder /app/apps/docs/.next/static ./apps/dashboard/.next/static

WORKDIR /app/apps/docs

EXPOSE 3000

CMD ["node", "server.js"]