FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY apps/docs/ ./apps/docs/
WORKDIR /app/apps/docs
RUN npm run build

FROM node:20-alpine AS runner

RUN addgroup --system app && adduser --system --ingroup app app

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /usr/local/lib/node_modules /usr/local/lib/node_modules

COPY --from=builder /app/apps/docs/package.json ./apps/docs/
COPY --from=builder /app/apps/docs/node_modules ./apps/docs/node_modules
COPY --from=builder /app/apps/docs/.next/standalone ./
COPY --from=builder /app/apps/docs/.next/static ./apps/docs/.next/static

WORKDIR /app/apps/docs

USER app

EXPOSE 3000

CMD ["node", "server.js"]
